import Link from "next/link";
import Provider from "./Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#FFFFFF",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head />
      <body>
        <Provider>
          <header>
            <h1>
              <Link href="/">ブログ</Link>
            </h1>
          </header>
          {children}
          <footer>
            <small>©️2023 hiroto</small>
          </footer>
        </Provider>
      </body>
    </html>
  );
}
